/*
 *  Copyright (c) 2020-2021 AtomLanguage Developers
 *  Distributed Under The MIT License
 */

OPCODE(PUSH_CONSTANT, 2, 1)

OPCODE(PUSH_NULL, 0, 1)

OPCODE(PUSH_0, 0, 1)

OPCODE(PUSH_TRUE, 0, 1)

OPCODE(PUSH_FALSE, 0, 1)

OPCODE(SWAP, 0, 0)

OPCODE(PUSH_LIST, 2, 1)

OPCODE(PUSH_MAP, 0, 1)

OPCODE(PUSH_INSTANCE, 1, 1)

OPCODE(LIST_APPEND, 0, -1)

OPCODE(MAP_INSERT, 0, -2)

OPCODE(INST_APPEND, 0, -1)

OPCODE(PUSH_LOCAL_0, 0, 1)
OPCODE(PUSH_LOCAL_1, 0, 1)
OPCODE(PUSH_LOCAL_2, 0, 1)
OPCODE(PUSH_LOCAL_3, 0, 1)
OPCODE(PUSH_LOCAL_4, 0, 1)
OPCODE(PUSH_LOCAL_5, 0, 1)
OPCODE(PUSH_LOCAL_6, 0, 1)
OPCODE(PUSH_LOCAL_7, 0, 1)
OPCODE(PUSH_LOCAL_8, 0, 1)
OPCODE(PUSH_LOCAL_N, 1, 1)

OPCODE(STORE_LOCAL_0, 0, 0)
OPCODE(STORE_LOCAL_1, 0, 0)
OPCODE(STORE_LOCAL_2, 0, 0)
OPCODE(STORE_LOCAL_3, 0, 0)
OPCODE(STORE_LOCAL_4, 0, 0)
OPCODE(STORE_LOCAL_5, 0, 0)
OPCODE(STORE_LOCAL_6, 0, 0)
OPCODE(STORE_LOCAL_7, 0, 0)
OPCODE(STORE_LOCAL_8, 0, 0)
OPCODE(STORE_LOCAL_N, 1, 0)

OPCODE(PUSH_GLOBAL, 1, 1)

OPCODE(STORE_GLOBAL, 1, 0)

OPCODE(PUSH_FN, 1, 1)

OPCODE(PUSH_TYPE, 1, 1)

OPCODE(PUSH_BUILTIN_FN, 1, 1)

OPCODE(POP, 0, -1)

OPCODE(IMPORT, 2, 1)

OPCODE(CALL, 1, -0) 

OPCODE(TAIL_CALL, 1, -0) 

OPCODE(ITER_TEST, 0, 0)

OPCODE(ITER, 3, 0)

OPCODE(JUMP, 2, 0)

OPCODE(LOOP, 2, 0)

OPCODE(JUMP_IF, 2, -1)

OPCODE(JUMP_IF_NOT, 2, -1)

OPCODE(RETURN, 0, -1)

OPCODE(GET_ATTRIB, 2, 0)

OPCODE(GET_ATTRIB_KEEP, 2, 1)

OPCODE(SET_ATTRIB, 2, -1)

OPCODE(GET_SUBSCRIPT, 0, -1)

OPCODE(GET_SUBSCRIPT_KEEP, 0, 1)

OPCODE(SET_SUBSCRIPT, 0, -2)

OPCODE(NEGATIVE, 0, 0) 
OPCODE(NOT, 0, 0)      
OPCODE(BIT_NOT, 0, 0)  

OPCODE(ADD, 0, -1)
OPCODE(SUBTRACT, 0, -1)
OPCODE(MULTIPLY, 0, -1)
OPCODE(DIVIDE, 0, -1)
OPCODE(MOD, 0, -1)

OPCODE(BIT_AND, 0, -1)
OPCODE(BIT_OR, 0, -1)
OPCODE(BIT_XOR, 0, -1)
OPCODE(BIT_LSHIFT, 0, -1)
OPCODE(BIT_RSHIFT, 0, -1)

OPCODE(EQEQ, 0, -1)
OPCODE(NOTEQ, 0, -1)
OPCODE(LT, 0, -1)
OPCODE(LTEQ, 0, -1)
OPCODE(GT, 0, -1)
OPCODE(GTEQ, 0, -1)

OPCODE(RANGE, 0, -1) 
OPCODE(IN, 0, -1)

OPCODE(REPL_PRINT, 0, 0)

OPCODE(END, 0, 0)