name: Build Atomlang In Linux

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Installing Deps
        run: |
          sudo apt-get update  
          sudo apt install gcc make
          
      - name: Building
        run: |
          make