name: Build Atomlang In Windows

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  bench:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Run Build Script
        run: |
          cmd /c bulid.bat
    