name: CI
on: [push, pull_request]

jobs:

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the Makefile.
        run: |
          make all

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build batch script.
        run: |
          cmd /c build.bat

  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the Makefile.
        run: |
          make all


